apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-pipeline
spec:
  serviceAccountName: jenkins-agent # Enter the service account name being used
  securityContext:
    runAsUser: 0
    fsGroup: 0
    runAsNonRoot: false
  containers:
  - name: jenkins-agent
    image: 975049994084.dkr.ecr.us-east-1.amazonaws.com/jenkins-ecr:jenkins-agent # Enter the jenkins inbound agent image.
    command:
    - sleep
    args:
    - 2h
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1024Mi
